// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDX-e4D4XY5Iv7egMY43-OlFAwlE0vE50',
    appId: '1:393955691593:web:04fbcb62764b16158a8398',
    messagingSenderId: '393955691593',
    projectId: 'flutter-app-689be',
    authDomain: 'flutter-app-689be.firebaseapp.com',
    storageBucket: 'flutter-app-689be.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsRAc1UAdRHmiiTYCuT58ZC_41fMPZPgo',
    appId: '1:393955691593:android:9130d84307f2de758a8398',
    messagingSenderId: '393955691593',
    projectId: 'flutter-app-689be',
    storageBucket: 'flutter-app-689be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQhKEiY2-xdDe-k9_TYt5_VGNPJOF7Uco',
    appId: '1:393955691593:ios:875b272235a551638a8398',
    messagingSenderId: '393955691593',
    projectId: 'flutter-app-689be',
    storageBucket: 'flutter-app-689be.appspot.com',
    iosBundleId: 'com.example.unitConversion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQhKEiY2-xdDe-k9_TYt5_VGNPJOF7Uco',
    appId: '1:393955691593:ios:875b272235a551638a8398',
    messagingSenderId: '393955691593',
    projectId: 'flutter-app-689be',
    storageBucket: 'flutter-app-689be.appspot.com',
    iosBundleId: 'com.example.unitConversion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDX-e4D4XY5Iv7egMY43-OlFAwlE0vE50',
    appId: '1:393955691593:web:4440ad8d91434cc18a8398',
    messagingSenderId: '393955691593',
    projectId: 'flutter-app-689be',
    authDomain: 'flutter-app-689be.firebaseapp.com',
    storageBucket: 'flutter-app-689be.appspot.com',
  );
}
